### ISSUE TITLE
dev branch error?

### ISSUE THREAD

**Issue by trislett** [mindandbrain/pipeline#37]
It seems the pipeline is still trying to calculate reho etc. even if it is not selected. 

The crash files are also being outputted to my home folder. I would suggest moving them to the output folder. I've attached one of them (needs to be unzipped).

I'm not sure if the resting state data finished processing.

[crash.zip](https://github.com/mindandbrain/pipeline/files/3711086/crash.zip)

Here's an example from the 30MB log file. 

```
RuntimeError: Command:
3dBandpass -prefix ./residual_filtered.nii.gz 0.009000 0.080000 /ext/mnt/mbServerProjects/SCRATCH/USERS/tris/ENIGMA_PIPELINE_INTEGRAMENT/OUTPUT_INTEGRAMENT/PROCESSED/nipype/sub_PIAB_XVKO4/task_rest/reho_wf/bandpass_filtering/reho_residuals.nii.gz
Standard output:

Standard error:
++ 3dBandpass: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m (-: For most purposes, 3dTproject is superior to 3dBandpass :-)
** ERROR (nifti_image_read): short header read '/ext/mnt/mbServerProjects/SCRATCH/USERS/tris/ENIGMA_PIPELINE_INTEGRAMENT/OUTPUT_INTEGRAMENT/PROCESSED/nipype/sub_PIAB_XVKO4/task_rest/reho_wf/bandpass_filtering/reho_residuals.nii.gz'
[7m** FATAL ERROR:[0m Can't open dataset '/ext/mnt/mbServerProjects/SCRATCH/USERS/tris/ENIGMA_PIPELINE_INTEGRAMENT/OUTPUT_INTEGRAMENT/PROCESSED/nipype/sub_PIAB_XVKO4/task_rest/reho_wf/bandpass_filtering/reho_residuals.nii.gz'
** Program compile date = Jun 12 2017
Return code: 1
```

and 

```
	 crashfile: /home/tris/crash-20191010-130823-tris-bandpass_filtering-7a6784bc-177f-4467-a1eb-60478f7e22f4.pklz
2019-10-10 13:08:45,902 nipype.workflow:INFO crashfile: /home/tris/crash-20191010-130823-tris-bandpass_filtering-7a6784bc-177f-4467-a1eb-60478f7e22f4.pklz
191010-13:08:45,903 nipype.workflow INFO:
	 ***********************************
2019-10-10 13:08:45,903 nipype.workflow:INFO ***********************************
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/pipeline", line 11, in <module>
    load_entry_point('pipeline==0.2.1.dev0', 'console_scripts', 'pipeline')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/pipeline-0.2.1.dev0-py3.6.egg/pipeline/run.py", line 484, in main
    workflow.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

```

**Comment by marcbue** [comment]
Thanks error should be fixed in the newest dev. If you want to rerun please delete the lines of reho and alff in your pipeline.json. I'll keep this issue open until we can confirm that the bug is indeed fixed (on my site it runs through).

**Comment by marcbue** [comment]
Since there seem to be another error with dev right now. This can't be tested. I'll update when we fixed that other issue

**Comment by ilyaveer** [comment]
This is fixed now
